version: '3.1'

services:

  app:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - backend

  db:
    image: mysql:8
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
    networks:
      - backend

networks:
  backend: