version: '3.1'

services:

  app:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    build: ./db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo